-- Quests
-- Summon Felsteed (Warlock)
DELETE FROM `disables`WHERE `sourceType`=1 AND `entry` IN (3631, 4487, 4488, 4489, 4490);

-- Arenas
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=4;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 4, 'Nagrand Arena / Ring of Trials');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=5;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 5, 'Blade\'s Edge Arena');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=6;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 6, 'Arenas');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=8;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 8, 'Ruins of Lordaeron');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=10;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 10, 'Dalaran Sewers');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=11;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 11, 'The Ring of Valor');

-- Battlegrounds
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=1;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 1, 'Alterac Valley');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=2;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 2, 'Warsong Gulch');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=3;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 3, 'Arathi Basin');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=7;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 7, 'Eye of the Storm');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=9;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 9, 'Strand of the Ancients');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=30;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 30, 'Isle of Conquest');
DELETE FROM `disables` WHERE `sourceType`=3 AND `entry`=32;
INSERT INTO `disables` (`sourceType`, `entry`, `comment`) VALUES (3, 32, 'Random Battleground');

-- Dungeons
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=349;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 349, 1, 'Maraudon');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=429;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 429, 1, 'Dire Maul');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=269;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 269, 3, 'Caverns Of Time: Black Morass');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=540;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 540, 3, 'The Shattered Halls');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=542;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 542, 3, 'The Blood Furnace');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=543;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 543, 3, 'Hellfire Ramparts');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=545;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 545, 3, 'The Steamvault');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=546;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 546, 3, 'The Underbog');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=547;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 547, 3, 'The Slave Pens');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=552;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 552, 3, 'The Arcatraz');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=553;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 553, 3, 'The Botanica');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=554;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 554, 3, 'The Mechanar');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=555;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 555, 3, 'Shadow Labyrinth');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=556;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 556, 3, 'Sethekk Halls');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=557;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 557, 3, 'Mana Tombs');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=558;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 558, 3, 'Auchenai Crypts');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=560;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 560, 3, 'Caverns Of Time: Old Hillsbrad Foothills');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=574;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 574, 3, 'Utgarde Keep');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=575;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 575, 3, 'Utgarde Pinnacle');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=576;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 576, 3, 'The Nexus');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=578;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 578, 3, 'The Oculus');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=585;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 585, 3, 'Magister\'s Terrace');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=595;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 595, 3, 'Culling of Stratholme');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=599;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 599, 3, 'Halls of Stone');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=600;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 600, 3, 'Drak\'Tharon Keep');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=601;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 601, 3, 'Azjol-Nerub');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=602;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 602, 3, 'Halls of Lightning');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=604;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 604, 3, 'Gundrak');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=608;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 608, 3, 'Violet Hold');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=619;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 619, 3, 'Ahn\'Kahet');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=632;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 632, 3, 'Forge of Souls');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=650;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 650, 3, 'Trial of the Champion');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=658;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 658, 3, 'Pit of Saron');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=668;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 668, 3, 'Halls of Reflection');

-- Raids
-- DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=249;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 249, 3, 'Onyxia\s Lair');
-- DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=309;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 309, 1, 'Zul\'Gurub');
-- DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=469;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 469, 1, 'Blackwing Lair');
-- DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=509;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 509, 1, 'Ruins of Ahn\'Qiraj');
-- DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=531;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 531, 1, 'Temple of Ahn\'Qiraj');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=532;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 532, 1, 'Karazhan');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=533;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 533, 3, 'Naxxramas');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=534;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 534, 1, 'Battle of Mount Hyjal');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=544;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 544, 1, 'Magtheridon\'s Lair');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=548;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 548, 1, 'Serpentshrine Cavern');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=550;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 550, 1, 'Tempest Keep');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=565;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 565, 1, 'Gruul\'s Lair');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=568;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 568, 1, 'Zul\'Aman');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=564;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 564, 1, 'Black Temple');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=580;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 580, 1, 'Sunwell Plateau');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=603;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 603, 3, 'Ulduar');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=615;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 615, 3, 'The Obsidian Sanctum');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=616;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 616, 3, 'Eye of Eternity');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=624;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 624, 3, 'Vault of Archavon');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=631;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 631, 15, 'Icecrown Citadel');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=649;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 649, 15, 'Trial of the Crusader');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=724;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 724, 15, 'The Ruby Sanctum');

-- Events
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=1;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 1, 0, 'Midsummer Fire Festival');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=2;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 2, 0, 'Winter Veil');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=3;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 3, 0, 'Darkmoon Faire (Terokkar Forest)');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=4;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 4, 0, 'Darkmoon Faire (Elwynn Forest)');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=5;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 5, 0, 'Darkmoon Faire (Mulgore)');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=6;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 6, 0, 'New Year\'s Eve');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=7;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 7, 0, 'Lunar Festival');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=8;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 8, 0, 'Love is in the Air');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=9;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 9, 0, 'Noblegarden');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=10;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 10, 0, 'Children\'s Week');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=11;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 11, 0, 'Harvest Festival');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=12;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 12, 0, 'Hallow\'s End');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=13;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 13, 0, 'Elemental Invasions');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=14;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 14, 0, 'Stranglethorn Fishing Extravaganza Announce');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=15;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 15, 0, 'Stranglethorn Fishing Extravaganza Fishing Pools');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=16;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 16, 0, 'Gurubashi Arena Booty Run');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=17;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 17, 0, 'Scourge Invasion');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=18;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 18, 0, 'Call to Arms: Alterac Valley!');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=19;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 19, 0, 'Call to Arms: Warsong Gulch!');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=20;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 20, 0, 'Call to Arms: Arathi Basin!');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=21;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 21, 0, 'Call to Arms: Eye of the Storm!');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=22;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 22, 0, 'AQ War Effort');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=23;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 23, 0, 'Darkmoon Faire Building (Elwynn Forest)');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=24;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 24, 0, 'Brewfest');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=25;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 25, 0, 'Pyrewood Village');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=26;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 26, 0, 'Pilgrim\'s Bounty');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=27;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 27, 0, 'Edge of Madness, Gri\'lek');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=28;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 28, 0, 'Edge of Madness, Hazza\'rah');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=29;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 29, 0, 'Edge of Madness, Renataki');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=30;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 30, 0, 'Edge of Madness, Wushoolay');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=31;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 31, 0, 'Arena Tournament');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=32;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 32, 0, 'L70ETC Concert');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=33;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 33, 0, 'Dalaran: Minigob');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=34;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 34, 0, 'Brew of the Month October');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=35;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 35, 0, 'Brew of the Month November');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=36;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 36, 0, 'Brew of the Month December');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=37;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 37, 0, 'Brew of the Month January');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=38;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 38, 0, 'Brew of the Month February');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=39;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 39, 0, 'Brew of the Month March');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=40;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 40, 0, 'Brew of the Month April');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=41;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 41, 0, 'Brew of the Month May');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=42;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 42, 0, 'Brew of the Month June');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=43;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 43, 0, 'Brew of the Month July');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=44;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 44, 0, 'Brew of the Month August');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=45;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 45, 0, 'Brew of the Month September');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=48;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 48, 0, 'Wintergrasp Alliance Defence');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=49;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 49, 0, 'Wintergrasp Horde Defence');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=50;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 50, 0, 'Pirates\' Day');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=51;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 51, 0, 'Day of the Dead');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=52;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 52, 0, 'Winter Veil: Gifts');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=53;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 53, 0, 'Call to Arms: Strand of the Ancients!');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=54;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 54, 0, 'Call to Arms: Isle of Conquest!');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=55;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 55, 0, 'Arena Season 3');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=56;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 56, 0, 'Arena Season 4');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=57;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 57, 0, 'Arena Season 5');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=58;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 58, 0, 'Arena Season 6');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=59;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 59, 0, 'Arena Season 7');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=60;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 60, 0, 'Arena Season 8');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=61;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 61, 0, 'Zalazane\'s Fall');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=62;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 62, 0, 'Stranglethorn Fishing Extravaganza Turn-ins');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=63;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 63, 0, 'Kalu\'ak Fishing Derby Turn-ins');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=64;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 64, 0, 'Kalu\'ak Fishing Derby Fishing Pools');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=65;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 65, 0, 'Venture Bay Alliance Defence');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=66;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 66, 0, 'Venture Bay Horde Defence');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=67;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 67, 0, 'AT Event Trigger (Tirion Speech)');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=68;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 68, 0, 'AT Event Trigger (Horde Event)');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=69;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 69, 0, 'AT Event Trigger (Alliance Event)');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=70;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 70, 0, 'Brewfest Building (Iron Forge)');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=71;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 71, 0, 'Darkmoon Faire Building (Mulgore)');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=73;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 73, 0, 'Hourly Bells');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=74;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 74, 0, 'Children of Goldshire');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=77;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 77, 0, 'Darkmoon Faire Building (Terokkar Forest)');
-- DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=78;
-- INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 78, 0, 'Summer seasonal fish');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=79;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 79, 0, 'Diurnal fishing event');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=80;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 80, 0, 'Nocturnal fishing event');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=85;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 85, 0, 'Stitches Event');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=86;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 86, 0, 'Perry Gatner');
DELETE FROM `disables` WHERE `sourceType`=9 AND `entry`=87;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (9, 87, 0, 'Scarlet Oracle');

-- Maps
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=530;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 530, 0, 'Outland');
DELETE FROM `disables` WHERE `sourceType`=2 AND `entry`=571;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES (2, 571, 0, 'Northrend');

-- Disable these quests to prevent db errors caused by max player level being 60
DELETE FROM `disables` WHERE `sourceType`=1 AND `entry` IN (10831, 10832, 10833, 10897, 10899, 10902, 10905, 10906, 10907, 11016, 11017, 11018, 12888, 12918, 12952, 12958, 12959, 12960, 12961, 12962, 12963, 13002, 13004, 13041, 13087, 13088, 13089, 13090, 13100, 13101, 13102, 13103, 13107, 13112, 13113, 13114, 13115, 13116, 13148, 13265, 13268, 13269, 13270, 13272, 13571, 14151);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10831);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10832);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10833);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10897);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10899);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10902);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10905);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10906);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 10907);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 11016);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 11017);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 11018);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12888);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12918);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12952);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12958);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12959);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12960);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12961);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12962);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 12963);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13002);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13004);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13041);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13087);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13088);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13089);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13090);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13100);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13101);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13102);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13103);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13107);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13112);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13113);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13114);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13115);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13116);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13148);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13265);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13268);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13269);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13270);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13272);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 13571);
INSERT INTO `disables` (`sourceType`, `entry`) VALUES (1, 14151);
